### ISSUE TITLE
Pareto-dominance fitness function

### ISSUE THREAD

**Issue by karinemiras** [ci-group/revolve2#100]

**Comment by surgura** [comment]
Can you describe what the requirements would be for such a function(or set or functions?) Maybe provide links to algorithms

**Comment by karinemiras** [comment]
It is simple: the function should calculate the number of dominated solutions of a solution (e.g., for each robot against all robots in the pop). Dominating means that it is not worse in any of the objectives and better in at least one. The number of objectives should be a param (as many as the user provides).

**Comment by surgura** [comment]
Ok so given an evaluated individual and an evaluated population, count the number of individuals in the population that are worse than the given individual, provided some user function over fitness.

**Comment by oliverweissl** [comment]
included in #381
