### ISSUE TITLE
New tutorials

### ISSUE THREAD

**Issue by surgura** [ci-group/revolve2#227]
The old tutorials(in the documentation, not the examples) are/will be soon wildly outdated.

**Comment by surgura** [comment]
For beta2 release we will use the new examples instead of writing tutorials. I think that is good enough for now. We want the release rather sooner than later.

**Comment by surgura** [comment]
@oliverweissl I think the examples + the current installation and getting started guide are sufficient. What do you think? I think we can close this issue.

**Comment by oliverweissl** [comment]
yes i think they are sufficient aswell, besides the RPI part which is WIP

**Comment by surgura** [comment]
yeah for all new features we should add new examples. and we can keep adding examples every time there are questions about things
