### ISSUE TITLE
Raspberry tutorials / examples

### ISSUE THREAD

**Issue by surgura** [ci-group/revolve2#249]

**Comment by oliverweissl** [comment]
I think we can close this? @surgura

**Comment by surgura** [comment]
let's wait for the remote control and v2 robots

**Comment by surgura** [comment]
- [ ] V1
- [ ] V2
- [ ] Creating configs and running manually (for experts).
- [ ] Using the remote control.
- [ ] How to build a physical core (for experts).
- [ ] How to create a physical robot.

**Comment by surgura** [comment]
How to create a core can be improved for V2. The robohat repo should be cleaned up to be clearer on what to do.
