### ISSUE TITLE
Cleanup physics actor

### ISSUE THREAD

**Issue by surgura** [ci-group/revolve2#253]
Some things can be improved.
- ~Some code duplication between bounding box and collision.~
- Modular robot to actor conversion is messy.
- ~Maybe remove pyrr? If not, maybe use pyrr AABB instead of bbox.~
- More?

**Comment by surgura** [comment]
AABB part will be solved in #277

**Comment by oliverweissl** [comment]
Modular robot-to-actor conversion is messy. is addressed in #294
