### ISSUE TITLE
Class diagram

### ISSUE THREAD

**Issue by surgura** [ci-group/revolve2#313]
For each package, so developers can easier understand.

**Comment by oliverweissl** [comment]
https://pylint.pycqa.org/en/latest/pyreverse.html

maybe this is useful

**Comment by surgura** [comment]
@oliverweissl In the most recent API update I also added inheritance graphs(images). Take a look and tell me if that is good enough? If it is, we can close this issues. E.g. look at the built docs for BodyV1
