### ISSUE TITLE
Make parameters for base modules mandatory in __init__

### ISSUE THREAD

**Issue by surgura** [ci-group/revolve2#325]
![image](https://github.com/ci-group/revolve2/assets/10170564/e241f23c-c8f4-4356-bd30-f334367f4177)
They're set here but let's set them in the parent __init__, because it's less error prone in the future.

**Comment by oliverweissl** [comment]
Im not sure if i understand, the ActiveHinge is already parent to the specific implementations. Where should the parameters get parsed then?

**Comment by surgura** [comment]
You are correct. My bad, for some reason I thought I was in ActiveHingeV2 when reading this file
