### ISSUE TITLE
can_set_child does not work properly for multiple slots

### ISSUE THREAD

**Issue by Nielssss99** [ci-group/revolve2#486]
**Describe the bug**
The function "can_set_child" evaluates whether a child can be set. In order to check this a convolution is applied, with an intended size of 2 x 2. However, the indexing gives you a 1 x 1 convolution which only evaluates the own slot.

**To Reproduce**
Build multiple slots. Check Mujoco viewer and you will see that neighbouring slots can both be occupied.

**Expected behavior**
According to the description neighbouring slots cannot be occupied.

* revolve2\modular_robot\revolve2\modular_robot\body\v2\_attachment_face_core_v2.py

* Solution
  for i, j in product(range(2), repeat=2):
      conv_check[i, j] = np.sum(check_matrix[i : (i + 2), j : (j + 2)])

**Comment by oliverweissl** [comment]
See #490
