### ISSUE TITLE
Querying Might not work properly

### ISSUE THREAD

**Issue by Nielssss99** [ci-group/revolve2#487]
**Describe the bug**
The Querying grid for the CPPN assumes four slots for the core module. However, in reality there are 9 slots. This leads to setting infeasible modules, which seem occasionally to lead to collision in Mujoco. Changing the core grid to 3 x 3 works better, but this might still lead to occupying non-available coordinates during querying. Better would be a function to assess whether a module can be placed based on the real coordinates of the already placed modules.

**To Reproduce**
Common sense

**Expected behavior**
Querying for whether a block could be placed or not should be accurate, preferably based on real coordinates occupied by the modules.

**Comment by oliverweissl** [comment]
See #405
