### ISSUE TITLE
Bricks are not square?

### ISSUE THREAD

**Issue by Nielssss99** [ci-group/revolve2#488]
**Describe the bug**
No idea whether it is a bug, but the bricks are not square: bounding_box=Vector3([0.06288625, 0.06288625, 0.0603])
See https://github.com/ci-group/revolve2/blob/master/modular_robot/revolve2/modular_robot/body/v2/_brick_v2.py.

**Comment by oliverweissl** [comment]
This is intended, the bricks in the reallife models are not square aswell. They have the same dimensions.
