### ISSUE TITLE
[BUG] Video in the wrong colorspace

### ISSUE THREAD

**Issue by kgd-al** [ci-group/revolve2#517]
**Describe the bug**
Video are generated in the mujoco colorspace (BGR) while cv2 expects RGB.

**To Reproduce**
Generate any video and compare blue/red colors

**Expected behavior**
Red should be red and blue should be blue.

Replacing https://github.com/ci-group/revolve2/blob/master/simulators/mujoco_simulator/revolve2/simulators/mujoco_simulator/_simulate_scene.py#L170
with 
```
img = cv2.cvtColor(np.flipud(img), cv2.COLOR_RGBA2BGR)
```
fixes the problem on my machine (see screenshots below).

**Screenshots**
Ground truth (viewer screenshot)
![Ground truth (viewer)](https://github.com/ci-group/revolve2/assets/17125058/91a038b4-0e62-4515-9c9e-f02906cd16e0)
Wrong colors in video
![Generated video](https://github.com/ci-group/revolve2/assets/17125058/94a9d810-54a3-4e6d-87d4-804ba3360bba)
After fixing offending line
![After color mapping](https://github.com/ci-group/revolve2/assets/17125058/ea4af700-0629-4157-bc2b-ed3f45c76286)

**Platform:**
 - OS: Linux 6.5.0-27-generic 28~22.04.1-Ubuntu
 - Python Version 3.10.12

**Comment by oliverweissl** [comment]
will investiaget --> numpy slicing might be better to avoid dependencies.

img  = img[:,:,::-1]

**Comment by kgd-al** [comment]
Isn't opencv already a dependency?
https://github.com/ci-group/revolve2/blob/master/simulators/mujoco_simulator/pyproject.toml#L34

**Comment by oliverweissl** [comment]
in that case disregard my comment :D
