### ISSUE TITLE
Speciation

### ISSUE THREAD

**Issue by surgura** [ci-group/revolve2#72]

**Comment by karinemiras** [comment]
We can use the same logic as neat speciation, however, allow us to choose which variables to use - originally it is done at the genotypic dimension, but what I'm most interested in is making it in the phenotypic and behavioral dimension. Can't we simply reuse matteo's code with some adaptations? Or maybe at least cheat from it.

**Comment by surgura** [comment]
Sure we can port it. Can you post a link to that code here?
