### ISSUE TITLE
morphological measures

### ISSUE THREAD

**Issue by karinemiras** [ci-group/revolve2#97]

**Comment by surgura** [comment]
Can you elaborate on what this means?

**Comment by karinemiras** [comment]
These are descriptors of body traits, and should be identical to the ones in Revolve 1, available here: https://github.com/ci-group/revolve/blob/plasticoding/pyrevolve/revolve_bot/measure/measure_body.py

**Comment by surgura** [comment]
A start on this has already been made with the analyzer: https://github.com/ci-group/revolve2/blob/master/core/revolve2/core/modular_robot/_analyzer.py
#108

**Comment by karinemiras** [comment]
Oh, so the concept of analyzer has changed? Before it had to do with collisions or so (I think).

**Comment by surgura** [comment]
Modular robot body has been refactored to make adding measures easier. Actually measures can be added by the people who need them on a demand basis and specific issues for each measure can be made
